server:
  forward-headers-strategy: framework

spring:
  mandatory-file-encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          jira:
            client-name: Jira
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET} 
            scope:
            - read:jira-user
            - read:jira-work
            redirect-uri: ${BASE_URL}/login/oauth2/code/jira
            authorization-grant-type: authorization_code
        provider:
          jira:
            authorization-uri: https://auth.atlassian.com/authorize?audience=api.atlassian.com&prompt=no
            token-uri: https://auth.atlassian.com/oauth/token

logging:
  file:
    path: ./logs
  logback:
    rollingpolicy:
      max-file-size: 1MB
      max-history: 10
      total-size-cap: 20MB
  level:
    root: info
