server:
  forward-headers-strategy: framework

spring:
  mandatory-file-encoding: UTF-8

logging:
  file:
    path: ./logs
  logback:
    rollingpolicy:
      max-file-size: 1MB
      max-history: 10
      total-size-cap: 20MB
  level:
    root: info
